version: '3.4'

services:
  CurrencyService:
    image: ${DOCKER_REGISTRY-}CurrencyService
    build:
      context: .
      dockerfile: CurrencyService/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1433:1433"

    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"