version: '3.4'
volumes:
  SqlServerVol:
    external: true
services:
  currencyservice:
    build:
      context: ./CurrencyService
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
    expose:
      - "80"
    ports:
        - "80:80"
  db:
    build:
      context: ./SQLServerContainer
      dockerfile: Dockerfile
    expose:
      - "1433"
    ports:
        - "1433:1433"
    volumes:
      - SqlServerVol:/var/opt/mssql
