version: '3.4'

services:
  currencyservice:
    build:
      context: ./CurrencyService
      dockerfile: Dockerfile
  db:
    build:
      context: ./SQLServerContainer
      dockerfile: Dockerfile
    expose:
      - "1433"
    ports:
        - "1433:1433"
   
